//price range

export const PRICE_RANGE = {
  min: 50000,
  max: 7000000,
};

//brands and models

export const BRANDS_AND_MODELS = {
  hyundai: [
    "grand-i10",
    "i20",
    "i10",
    "creta",
    "verna",
    "eon",
    "venue",
    "xcent",
    "grand-i10-nios",
    "santro-xing",
    "alcazar",
    "aura",
    "new-santro-11",
    "elantra",
    "tucson",
    "accent",
    "exter",
    "getz-prime",
    "neo-fluidic-elantra",
    "santa-fe",
    "venue-nline",
  ],
  maruti: [
    "wagon-r",
    "swift",
    "baleno",
    "celerio",
    "alto",
    "alto-800",
    "ritz",
    "dzire",
    "ertiga",
    "ciaz",
    "brezza",
    "estilo",
    "s-cross",
    "eeco",
    "ignis",
    "a-star",
    "s-presso",
    "celerio-x",
    "grand-vitara",
    "xl6",
    "1000",
    "800",
    "esteem",
    "fronx",
    "jimny",
    "new-ertiga",
    "omni",
    "sx4",
    "versa",
    "zen",
  ],
  datsun: ["go", "go plus"],
  tata: [
    "tiago",
    "nexon",
    "altroz",
    "nano",
    "safari",
    "zest",
    "tigor",
    "harrier",
    "hexa",
    "punch",
    "aria",
    "bolt",
    "indica-ev2",
    "indica-v2",
    "indica-vista",
    "indicab",
    "indigo-cs",
    "indigo-ecs",
    "manza",
    "movus",
    "nano-genx",
    "safari-storme",
    "sumo-grande",
    "sumo-grande-mk-ii",
    "sumo-spacio",
    "sumo-victa",
    "tiago-nrg",
    "venture",
    "vista-tech",
  ],
  ford: [
    "ecosport",
    "figo",
    "freestyle",
    "figo-aspire",
    "endeavour",
    "classic",
    "escort",
    "fiesta",
    "fiesta-classic",
    "fusion",
    "mustang",
  ],
  renault: [
    "triber",
    "duster",
    "kiger",
    "captur",
    "scala",
    "fluence",
    "koleos",
    "lodgy",
    "pulse",
  ],
  chevrolet: [
    "spark",
    "aveo",
    "aveo-u-va",
    "cruze",
    "enjoy",
    "optra-magnum",
    "optra-srv",
    "sail",
    "sail-hatchback",
    "sail-u-va",
    "tavera",
    "trailblazer",
  ],
  volkswagen: [
    "vento",
    "taigun",
    "ameo",
    "virtus",
    "1600",
    "beetle",
    "cross-polo",
    "jetta",
    "passat",
    "phaeton",
    "t-roc",
    "tiguan",
    "tiguan-allspace",
    "touareg",
  ],
  volvo: ["s60", "xc40", "s80", "v40", "xc60", "xc90"],
  audi: [
    "a3",
    "a4",
    "q3",
    "a3-cabriolet",
    "a6",
    "a6-matrix",
    "q2",
    "q5",
    "q7",
    "r8",
    "rs5",
    "rs6",
    "rs7-sportback",
    "s5-sportback",
  ],
  "land rover": ["discovery-sport", "discovery", "discovery-3", "discovery-4"],
  "mg motors": ["gloster", "hector", "astor", "hector-plus"],
  skoda: [
    "rapid",
    "kushaq",
    "slavia",
    "superb",
    "fabia",
    "octavia",
    "fabia-scout",
    "karoq",
    "kodiaq",
    "laura",
    "octavia-combi",
  ],
  nissan: [
    "sunny",
    "micra",
    "kicks",
    "magnite",
    "micra-active",
    "terrano",
    "350z",
    "370z",
    "evalia",
    "teana",
  ],
  mercedes: [
    "c-class",
    "cla",
    "gla",
    "glc",
    "a-class",
    "amg-gt",
    "b-class",
    "e-class",
    "e-class-cabriolet",
    "gl",
    "gle",
    "gle-coupe",
    "gls",
    "ml-class",
    "s-coupe",
  ],
  toyota: [
    "c-class",
    "cla",
    "gla",
    "glc",
    "a-class",
    "amg-gt",
    "b-class",
    "e-class",
    "e-class-cabriolet",
    "gl",
    "gle",
    "gle-coupe",
    "gls",
    "ml-class",
    "s-coupe",
  ],
  kia: ["seltos", "sonet", "carens"],
  mahindra: [
    "xuv500",
    "xuv-300",
    "kuv100",
    "scorpio",
    "thar",
    "tuv300",
    "bolero",
    "bolero-neo",
    "scorpio-n",
    "xuv700",
    "alturas-g4",
    "armada",
    "e2o",
    "kuv100-nxt",
    "marazzo",
    "marshal",
    "nuvosport",
    "quanto",
    "revai",
    "scorpio-classic",
    "scorpio-getaway",
    "tuv-300-plus",
    "xylo",
  ],
  bmw: [
    "5-series",
    "x1",
    "3-series",
    "x3",
    "3-series-gt",
    "2-series-gran-coupe",
    "4-series",
    "5-series-gt",
    "6-series",
    "7-series",
    "8-series",
    "i8",
    "m3",
    "m5",
    "x4",
    "x5",
    "x6",
  ],
};

//years
export const YERAS = ["2020", "2018", "2016", "2014", "2012", "2010", "2008"];

//location
export const CITIES = [
  "Delhi NCR",
  "Mumbai",
  "Delhi",
  "Kolkata",
  "Chennai",
  "Bangalore",
  "Hyderabad",
  "Ahmedabad",
  "Pune",
  "Noida",
  "Gurugram",
];

//kms driven

export const DISTANCE = [
  "10000",
  "30000",
  "50000",
  "75000",
  "100000",
  "125000",
  "150000",
];

//Feul type
export const FUEL_TYPE = ["Petrol", "Diesel", "CNG"];
//Body type
export const BODY_TYPE = ["Hatchback", "Sedan", "SUV", "MUV"];
//transmission
export const TRANSMISSION = ["Automatic", "Manual"];
//owner
export const OWNER = ["1", "2", "3"];
